import { TInventoryItem } from "../../../(types)/TInventoryItem";

const dummyData: TInventoryItem[] = [
  {
    id: 1,
    name: "Laptop",
    assignedQuantity: 15,
    unassignedQuantity: -5,
    price: 999.99,
  },
  {
    id: 2,
    name: "Smartphone",
    assignedQuantity: 20,
    unassignedQuantity: 20,
    price: 699.99,
  },
  {
    id: 3,
    name: "Headphones",
    assignedQuantity: 5,
    unassignedQuantity: 10,
    price: 149.99,
  },
  {
    id: 4,
    name: "Tablet",
    assignedQuantity: 15,
    unassignedQuantity: 5,
    price: 499.99,
  },
  {
    id: 5,
    name: "Camera",
    assignedQuantity: 2,
    unassignedQuantity: 8,
    price: 799.99,
  },
];

// {
//   id: 6,
//   name: "Smartwatch",
//   assignedQuantity: 10,
//   unassignedQuantity: 20,
//   price: 299.99,
// },
// {
//   id: 7,
//   name: "Speaker",
//   assignedQuantity: 8,
//   unassignedQuantity: 4,
//   price: 199.99,
// },
// {
//   id: 8,
//   name: "External Hard Drive",
//   assignedQuantity: 12,
//   unassignedQuantity: 6,
//   price: 129.99,
// },
// {
//   id: 9,
//   name: "Gaming Console",
//   assignedQuantity: 5,
//   unassignedQuantity: 3,
//   price: 499.99,
// },
// {
//   id: 10,
//   name: "Wireless Earbuds",
//   assignedQuantity: 20,
//   unassignedQuantity: 15,
//   price: 129.99,
// },
// {
//   id: 11,
//   name: "Monitor",
//   assignedQuantity: 18,
//   unassignedQuantity: 4,
//   price: 299.99,
// },
// {
//   id: 12,
//   name: "Printer",
//   assignedQuantity: 10,
//   unassignedQuantity: 5,
//   price: 199.99,
// },
// {
//   id: 13,
//   name: "Keyboard",
//   assignedQuantity: 15,
//   unassignedQuantity: 5,
//   price: 79.99,
// },
// {
//   id: 14,
//   name: "Mouse",
//   assignedQuantity: 25,
//   unassignedQuantity: 5,
//   price: 49.99,
// },
// {
//   id: 15,
//   name: "Router",
//   assignedQuantity: 5,
//   unassignedQuantity: 5,
//   price: 149.99,
// },
// {
//   id: 16,
//   name: "Fitness Tracker",
//   assignedQuantity: 20,
//   unassignedQuantity: 5,
//   price: 149.99,
// },
// {
//   id: 17,
//   name: "External SSD",
//   assignedQuantity: 10,
//   unassignedQuantity: 5,
//   price: 199.99,
// },
// {
//   id: 18,
//   name: "Graphics Card",
//   assignedQuantity: 2,
//   unassignedQuantity: 3,
//   price: 999.99,
// },
// {
//   id: 19,
//   name: "Wireless Charger",
//   assignedQuantity: 15,
//   unassignedQuantity: 5,
//   price: 39.99,
// },
// {
//   id: 20,
//   name: "Power Bank",
//   assignedQuantity: 25,
//   unassignedQuantity: 5,
//   price: 79.99,
// },

export default dummyData;
