"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { useEffect } from "react";
import { FirebaseContext, app } from "./(context)/FirebaseContext";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "WMS Jaya Laksa Lestari",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    document.title = "Jaya Laksa Lestari";
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseContext.Provider value={app}>
          {children}
        </FirebaseContext.Provider>
      </body>
    </html>
  );
}
